### ISSUE TITLE
Rails 4.1.8 - Incompatibility

### ISSUE THREAD

**Issue by evandrodp** [before-actions-gem/before_actions#1]
Hello, 

I'm trying to load ruby 2.1.0, with rails 4.1.8.

/home/deployer/apps/app_production/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `require': No such file to load -- before_actions/application_controller (LoadError)

**Comment by ch1ago** [comment]
Thank you for pointing that out here,
That was only fixed a few weeks ago :+1: 
https://github.com/before-actions-gem/before_actions/blob/master/gemfiles/rails-4-1-stable.gemfile.lock
